[page]
title = "Smart Forms"
description = "SAP forms technology from 2001. Allows to create forms that contain custom logic and layout."
reason = "Not recommended. Legacy technology with restrictions regarding modern layout like barcodes or pictures. Once the dominant forms technology, SAPscript is superseded by SmartForms or Adobe Forms. Being a legacy technology means that its usage share is declining, making it also complicated to maintain SAPscript based forms. General recommendation is to migrate SAPscript forms or to rewrite them in newer technology."
support "Supported at least till 2040 (follows S/4HANA maintenance strategy)"

[links]
"SAP Help" = "https://help.sap.com/docs/SAP_NETWEAVER_AS_ABAP_752/e0ef07e1f76b4370b1baa502eace5ece/4e50b68d95e14dd2e10000000a42189b.html?locale=en-US&version=7.52.11"

[config]
label = "Smart Forms"
ring = "HOLD"
quadrant = "Technology"
active = true
moved = 0
